
spring:
  datasource:
    username: sa_test
    driver-class-name: com.mysql.jdbc.Driver
    password: ymtcs@2016
    url: jdbc:mysql://172.16.101.211:30001/xlobocustomer?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
      com.example: trace
  file:
    path: /springboot/log