package com.example.crud.demo.entity;

import java.util.Date;

public class TestActivityEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.ActivityId
     *
     * @mbggenerated
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.ActivityName
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.StartTime
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.EndTime
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testactivity.RainSeconds
     *
     * @mbggenerated
     */
    private Long rainSeconds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.Id
     *
     * @return the value of testactivity.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.Id
     *
     * @param id the value for testactivity.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.ActivityId
     *
     * @return the value of testactivity.ActivityId
     *
     * @mbggenerated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.ActivityId
     *
     * @param activityId the value for testactivity.ActivityId
     *
     * @mbggenerated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.ActivityName
     *
     * @return the value of testactivity.ActivityName
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.ActivityName
     *
     * @param activityName the value for testactivity.ActivityName
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.StartTime
     *
     * @return the value of testactivity.StartTime
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.StartTime
     *
     * @param startTime the value for testactivity.StartTime
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.EndTime
     *
     * @return the value of testactivity.EndTime
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.EndTime
     *
     * @param endTime the value for testactivity.EndTime
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testactivity.RainSeconds
     *
     * @return the value of testactivity.RainSeconds
     *
     * @mbggenerated
     */
    public Long getRainSeconds() {
        return rainSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testactivity.RainSeconds
     *
     * @param rainSeconds the value for testactivity.RainSeconds
     *
     * @mbggenerated
     */
    public void setRainSeconds(Long rainSeconds) {
        this.rainSeconds = rainSeconds;
    }
}